import getConfig from 'next/config'
import Head from "next/head";
import Link from 'next/link'
import styles from "../styles/Home.module.css";

// ...holds access token
const { serverRuntimeConfig } = getConfig()

interface HomeProps {
  formTitles: string[];
}

export async function getStaticProps() {
  // ...step 2: fetch some data from VideoAsk API
  const headers = new Headers();
  headers.append("Authorization", `Bearer ${serverRuntimeConfig.store.token}`);
  
  var requestOptions: RequestInit = {
    method: 'GET',
    headers,
    redirect: 'follow'
  };

  const res = await fetch(`${process.env.VIDEOASK_API_BASE_URL}/forms?limit=0&offset=0&title=`, requestOptions);
  const data = await res.json();

  const formTitles: string[] = [];

  if (data.results) {
    for (const form of data.results) {
      formTitles.push(form.title)
    }

    formTitles.sort();
  }

  return {
    props: { formTitles }
  }
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h2 className={styles.centeredText}>All Forms</h2>
          <ul>
            {props.formTitles.map((formTitle) => <li key={formTitle}>{formTitle}</li>)}
          </ul>
        </div>

        <div>
          <h2 className={styles.centeredText}>Other Pages</h2>
          <Link href="/vote">
            <a>Vote Example Page</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
